name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build docker image
      run: | 
        docker build -t employee-rest-api .
    - name: run docker
      run: |
        docker run -p 5000:5000 -d employee-rest-api
    - name: check docker process
      run: |
        docker ps
    - name: run unit test
      run: |
        python3 test.py
    - name: run CRUD operations
      run: |
        python3 CRUD_ops_test.py
        
      
