name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: | 
        docker build -t employee-rest-api .
        
    - name: docker run
      run: |
        docker run -p 5000:5000 -d employee-rest-api
    - name: run test
      run: |
        ./test.sh
        
      
