name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER }}
        DOCKER_PASS: ${{secrets.DOCKER_PASSWORD }}
    - name: docker build
      run: | 
        docker build -t employee-rest-api .
        
    - name: docker run
      run: |
        docker run -p 5000:5000 employee-rest-api
      
