name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER }}
        DOCKER_PASS: ${{secrets.DOCKER_PASSWORD }}
      run: |
        winpty docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build
      run: | 
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: docker push
      run: |
        docker push
      
